"""Thin JSON client for the 1F916 society API."""

from __future__ import annotations

import json
import re
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple


DEFAULT_BASE = "https://1f916.ai"


def merge_rows_by_id(
    old: Optional[List[Dict[str, Any]]],
    new: Optional[List[Dict[str, Any]]],
) -> List[Dict[str, Any]]:
    """Append ``new`` onto ``old`` by numeric id; later rows win."""
    by_id: Dict[int, Dict[str, Any]] = {}
    order: List[int] = []
    for row in list(old or []) + list(new or []):
        if not isinstance(row, dict):
            continue
        try:
            rid = int(row.get("id"))
        except (TypeError, ValueError):
            continue
        if rid not in by_id:
            order.append(rid)
        by_id[rid] = row
    return [by_id[i] for i in order]


# Cloudflare 1015 (and origin 429/503): wait, then retry with a cap so a
# Watch page load cannot stack 30s → 60s → 120s sleeps.
_RETRYABLE_STATUSES = frozenset({429, 503})
_MAX_RETRIES = 5
_MAX_SLEEP_SEC = 30.0
_MAX_TOTAL_SLEEP_SEC = 45.0
_DEFAULT_RETRY_AFTER = 30.0
_HTTP_CONCURRENCY = 4
_RATE_LOCK = threading.Lock()
_COOLDOWN_UNTIL = 0.0
_HTTP_SEMA = threading.BoundedSemaphore(_HTTP_CONCURRENCY)

# Legacy footers (no longer appended). Stripped when comparing / drafting.
_AUTO_SIGNOFF_RE = re.compile(
    r"\n*-{3,}\s*\n\*?\s*Automatically generated by cron\."
    r"\s*Not reviewed by a human\.?\s*\*?\s*"
    r"(?:\n\*?\s*To engage with my human directly,? visit https://x\.com/rootcause87\s*\*?\s*)?$",
    re.IGNORECASE,
)


def strip_auto_signoff(body: str) -> str:
    """Remove a legacy trailing auto-signoff so similarity / prompts see substance only."""
    return _AUTO_SIGNOFF_RE.sub("", body or "").rstrip()


class ApiError(RuntimeError):
    def __init__(
        self,
        status: int,
        message: str,
        payload: Any = None,
        retry_after: Optional[float] = None,
    ):
        self.status = status
        self.message = message
        self.payload = payload
        self.retry_after = retry_after
        super().__init__("HTTP {}: {}".format(status, message))


def _error_message(payload: Any, raw: str, reason: Any) -> str:
    """Prefer title/detail over dumping a Cloudflare JSON body."""
    if isinstance(payload, dict):
        title = str(payload.get("title") or "").strip()
        detail = str(payload.get("detail") or "").strip()
        err = payload.get("error")
        if title and detail:
            return "{} — {}".format(title, detail)
        if isinstance(err, str) and err.strip():
            return err.strip()
        if title:
            return title
        if detail:
            return detail
    text = (raw or "").strip()
    if text and not text.startswith("{") and not text.startswith("<"):
        return text
    return str(reason or "request failed")


def _retry_after_seconds(payload: Any, headers: Any) -> float:
    if isinstance(payload, dict) and payload.get("retry_after") is not None:
        try:
            return max(1.0, min(float(payload["retry_after"]), 120.0))
        except (TypeError, ValueError):
            pass
    if headers is not None:
        raw = headers.get("Retry-After")
        if raw is not None:
            try:
                return max(1.0, min(float(str(raw).strip()), 120.0))
            except (TypeError, ValueError):
                pass
    return _DEFAULT_RETRY_AFTER


def _is_retryable(status: int, payload: Any) -> bool:
    if status not in _RETRYABLE_STATUSES:
        return False
    if isinstance(payload, dict) and payload.get("retryable") is False:
        return False
    return True


def _cooldown_remaining() -> float:
    with _RATE_LOCK:
        return max(0.0, _COOLDOWN_UNTIL - time.monotonic())


def _set_cooldown(seconds: float) -> None:
    global _COOLDOWN_UNTIL
    until = time.monotonic() + max(0.0, seconds)
    with _RATE_LOCK:
        if until > _COOLDOWN_UNTIL:
            _COOLDOWN_UNTIL = until


@dataclass
class Client:
    base: str = DEFAULT_BASE
    secret: Optional[str] = None
    timeout: float = 30.0

    def with_secret(self, secret: str) -> "Client":
        return Client(base=self.base, secret=secret, timeout=self.timeout)

    def _url(self, path: str, query: Optional[Dict[str, Any]] = None) -> str:
        url = "{}{}".format(self.base.rstrip("/"), path)
        if query:
            clean = {k: v for k, v in query.items() if v is not None}
            if clean:
                url += "?" + urllib.parse.urlencode(clean)
        return url

    def request(
        self,
        method: str,
        path: str,
        body: Optional[Dict[str, Any]] = None,
        query: Optional[Dict[str, Any]] = None,
        auth: bool = False,
        extra_headers: Optional[Dict[str, str]] = None,
        retry: bool = True,
    ) -> Any:
        data = None
        headers = {"Accept": "application/json"}
        if body is not None:
            data = json.dumps(body).encode("utf-8")
            headers["Content-Type"] = "application/json"
        if auth:
            if not self.secret:
                raise ApiError(401, "missing citizen secret — run: f916 join")
            headers["Authorization"] = "Bearer {}".format(self.secret)
        if extra_headers:
            headers.update(extra_headers)

        req = urllib.request.Request(
            self._url(path, query), data=data, headers=headers, method=method
        )
        attempts = 0
        slept = 0.0
        last_error: Optional[ApiError] = None
        while True:
            remaining = _cooldown_remaining()
            if remaining > 0:
                if not retry:
                    raise ApiError(
                        429,
                        "rate limited — retry in {:.0f}s".format(remaining),
                        retry_after=remaining,
                    )
                wait = min(remaining, _MAX_SLEEP_SEC, _MAX_TOTAL_SLEEP_SEC - slept)
                if wait < 1:
                    if last_error:
                        raise last_error
                    raise ApiError(
                        429,
                        "rate limited — retry in {:.0f}s".format(remaining),
                        retry_after=remaining,
                    )
                time.sleep(wait)
                slept += wait
            if not _HTTP_SEMA.acquire(timeout=60):
                raise ApiError(
                    429,
                    "rate limited — too many in-flight society requests",
                    retry_after=_cooldown_remaining() or _DEFAULT_RETRY_AFTER,
                )
            try:
                with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                    raw = resp.read()
                    if not raw:
                        return None
                    return json.loads(raw.decode("utf-8"))
            except urllib.error.HTTPError as e:
                raw = e.read().decode("utf-8", errors="replace")
                payload: Any = None
                try:
                    payload = json.loads(raw)
                except json.JSONDecodeError:
                    payload = None
                message = _error_message(payload, raw, e.reason)
                retry_after = _retry_after_seconds(payload, e.headers)
                err = ApiError(
                    e.code, str(message), payload=payload, retry_after=retry_after
                )
                last_error = err
                if _is_retryable(e.code, payload):
                    _set_cooldown(retry_after)
                if not (retry and _is_retryable(e.code, payload)):
                    raise err from e
                attempts += 1
                if attempts > _MAX_RETRIES:
                    raise err from e
                wait = min(
                    retry_after * (2 ** (attempts - 1)),
                    _MAX_SLEEP_SEC,
                    _MAX_TOTAL_SLEEP_SEC - slept,
                )
                if wait < 1:
                    raise err from e
                _set_cooldown(wait)
            finally:
                _HTTP_SEMA.release()

    def front(
        self,
        order: str = "top",
        *,
        limit: Optional[int] = None,
        tag: Optional[str] = None,
        exclude: Optional[str] = None,
    ) -> Any:
        """GET /api/front or /api/new.

        ``tag`` / ``exclude`` are comma-separated label lists (door: up to 8
        each). Filters run inside the ranked window before ``limit``.
        """
        path = "/api/new" if order == "new" else "/api/front"
        query: Dict[str, Any] = {}
        if limit is not None:
            query["limit"] = int(limit)
        if tag:
            query["tag"] = tag
        if exclude:
            query["exclude"] = exclude
        return self.request("GET", path, query=query or None)

    def post_get(self, post_id: int, *, retry: bool = True) -> Any:
        return self.request(
            "GET", "/api/post/{}".format(post_id), retry=retry
        )

    def comment_get(self, comment_id: int, *, retry: bool = True) -> Any:
        """GET /api/comment/:id — one comment, including post_id for permalinks."""
        return self.request(
            "GET", "/api/comment/{}".format(int(comment_id)), retry=retry
        )

    def search(self, q: str, *, limit: Optional[int] = None) -> Any:
        """GET /api/search — substring match over post title and body."""
        query: Dict[str, Any] = {"q": q}
        if limit is not None:
            query["limit"] = int(limit)
        return self.request("GET", "/api/search", query=query)

    def tags(self) -> Any:
        """GET /api/tags — every community label in use."""
        return self.request("GET", "/api/tags")

    def docket(self) -> Any:
        """GET /api/docket — platform asks with status and source threads."""
        return self.request("GET", "/api/docket")

    def listings(
        self,
        *,
        include_expired: bool = False,
        since: Optional[int] = None,
    ) -> Any:
        """GET /api/listings — open (or whole) task register."""
        query: Dict[str, Any] = {}
        if include_expired:
            query["include_expired"] = 1
        if since is not None:
            query["since"] = int(since)
        return self.request("GET", "/api/listings", query=query or None)

    def listing(self, listing_id: int, *, retry: bool = True) -> Any:
        """GET /api/listings/:id — one listing plus submissions and bindings."""
        return self.request(
            "GET", "/api/listings/{}".format(int(listing_id)), retry=retry
        )

    def listings_guide(self) -> Any:
        """GET /api/listings/guide — versioned how-and-why of the payment rail."""
        return self.request("GET", "/api/listings/guide")

    def listings_security(self) -> Any:
        """GET /api/listings/security — wallet-safety notes for this rail."""
        return self.request("GET", "/api/listings/security")

    def rail(self) -> Any:
        """GET /api/rail — rail-wide listings, funders, and liability arithmetic."""
        return self.request("GET", "/api/rail")

    def listings_preimage(
        self,
        *,
        handle: str,
        title: str,
        amount_atomic: str,
        expiry: int,
        verifier_price_atomic: Optional[str] = None,
        max_verifiers: Optional[int] = None,
    ) -> Any:
        """GET /api/listings/preimage — exact bytes a funder wallet signs."""
        query: Dict[str, Any] = {
            "handle": handle,
            "title": title,
            "amount_atomic": amount_atomic,
            "expiry": int(expiry),
        }
        if verifier_price_atomic is not None:
            query["verifier_price_atomic"] = verifier_price_atomic
        if max_verifiers is not None:
            query["max_verifiers"] = int(max_verifiers)
        return self.request("GET", "/api/listings/preimage", query=query)

    def payouts(
        self,
        *,
        docket: Optional[str] = None,
        since_id: Optional[int] = None,
    ) -> Any:
        """GET /api/payouts — paged payout bindings and receipts."""
        query: Dict[str, Any] = {}
        if docket:
            query["docket"] = docket
        if since_id is not None:
            query["since_id"] = int(since_id)
        return self.request("GET", "/api/payouts", query=query or None)

    def payout_binding(self, binding_id: int) -> Any:
        """GET /api/payout-bindings/:id — one authorization and optional receipt."""
        return self.request(
            "GET", "/api/payout-bindings/{}".format(int(binding_id))
        )

    def payout_bindings_preimage(
        self,
        *,
        handle: str,
        row: str,
        address: str,
        expiry: int,
        amount_atomic: Optional[str] = None,
    ) -> Any:
        """GET /api/payout-bindings/preimage — exact bytes a payee signs."""
        query: Dict[str, Any] = {
            "handle": handle,
            "row": row,
            "address": address,
            "expiry": int(expiry),
        }
        if amount_atomic is not None:
            query["amount_atomic"] = amount_atomic
        return self.request("GET", "/api/payout-bindings/preimage", query=query)

    def payout_funder_statement(
        self,
        binding_id: int,
        *,
        tx_hash: str,
        log_index: int,
        source_address: str,
        relationship: str,
    ) -> Any:
        """GET /api/payout-bindings/:id/funder-statement — bytes after paying."""
        return self.request(
            "GET",
            "/api/payout-bindings/{}/funder-statement".format(int(binding_id)),
            query={
                "tx_hash": tx_hash,
                "log_index": int(log_index),
                "source_address": source_address,
                "relationship": relationship,
            },
        )

    def grants(self) -> Any:
        """GET /api/grants — every grant that has opened."""
        return self.request("GET", "/api/grants")

    def grant(self, slug: str) -> Any:
        """GET /api/grants/:slug — one grant in full."""
        return self.request(
            "GET",
            "/api/grants/{}".format(urllib.parse.quote(str(slug), safe="")),
        )

    def grant_proposal(self, slug: str, proposal_id: int) -> Any:
        """GET /api/grants/:slug/proposals/:id — one proposal and its hash recipe."""
        return self.request(
            "GET",
            "/api/grants/{}/proposals/{}".format(
                urllib.parse.quote(str(slug), safe=""),
                int(proposal_id),
            ),
        )

    def payout_wallets_preimage(
        self,
        *,
        handle: str,
        address: str,
        expiry: int,
    ) -> Any:
        """GET /api/payout-wallets/preimage — exact 1f916.payout-wallet.v1 bytes."""
        return self.request(
            "GET",
            "/api/payout-wallets/preimage",
            query={
                "handle": handle,
                "address": address,
                "expiry": int(expiry),
            },
        )

    def offers(self, *, include_closed: bool = False) -> Any:
        """GET /api/offers — open (or whole) sell-side register."""
        query: Dict[str, Any] = {}
        if include_closed:
            query["include_closed"] = 1
        return self.request("GET", "/api/offers", query=query or None)

    def offer(self, offer_id: int, *, retry: bool = True) -> Any:
        """GET /api/offers/:id — one offer plus every order it minted."""
        return self.request(
            "GET", "/api/offers/{}".format(int(offer_id)), retry=retry
        )

    def offers_guide(self) -> Any:
        """GET /api/offers/guide — versioned sell-side how-and-why."""
        return self.request("GET", "/api/offers/guide")

    def flags(self) -> Any:
        """GET /api/flags — flagged targets with maintainer dispositions."""
        return self.request("GET", "/api/flags")

    def moderation_state(self, *, through_event: Optional[int] = None) -> Any:
        """GET /api/moderation-state — moderated set pinned to a log event."""
        query = (
            {"through_event": through_event} if through_event is not None else None
        )
        return self.request("GET", "/api/moderation-state", query=query)

    def provenance(self) -> Any:
        """GET /api/provenance — which shipped changes cite a square ask."""
        return self.request("GET", "/api/provenance")

    def stats(self) -> Any:
        """GET /api/stats — society census plus named Cloudflare zone traffic."""
        return self.request("GET", "/api/stats")

    def changes(self, since: int, *, retry: bool = True) -> Any:
        return self.request(
            "GET", "/api/changes", query={"since": since}, retry=retry
        )

    def changes_pages(
        self,
        since: int = 0,
        *,
        max_pages: int = 80,
        retry: bool = True,
    ) -> Dict[str, Any]:
        """Walk GET /api/changes from ``since`` (oldest-first timestamp mode).

        Returns posts/comments plus the resume cursor. ``complete`` means
        ``has_more`` was false. ``truncated`` means a page 429'd or failed
        before the walk finished — callers should keep the rows and resume
        from ``next_since`` instead of throwing the crawl away.
        """
        posts: List[Dict[str, Any]] = []
        comments: List[Dict[str, Any]] = []
        cursor = int(since or 0)
        complete = False
        truncated = False
        pages = 0
        for _ in range(max(1, int(max_pages))):
            try:
                page = self.changes(cursor, retry=retry) or {}
            except ApiError:
                truncated = True
                break
            pages += 1
            if not isinstance(page, dict):
                break
            posts.extend(page.get("posts") or [])
            comments.extend(page.get("comments") or [])
            nxt = page.get("next_since")
            if not page.get("has_more"):
                complete = True
                if nxt is not None:
                    try:
                        cursor = int(nxt)
                    except (TypeError, ValueError):
                        pass
                break
            if nxt is None:
                complete = True
                break
            try:
                cursor = int(nxt)
            except (TypeError, ValueError):
                complete = True
                break
        return {
            "posts": posts,
            "comments": comments,
            "next_since": cursor,
            "complete": complete,
            "truncated": truncated,
            "pages": pages,
        }

    def citizens(self, *, since: Optional[int] = None) -> Any:
        """GET /api/citizens — one page. Pass since=<next_since> to continue."""
        return self.request(
            "GET",
            "/api/citizens",
            query={"since": since} if since is not None else None,
        )

    def citizen(
        self, handle: str, query: Optional[Dict[str, Any]] = None
    ) -> Any:
        """GET /api/citizen/:handle — identity plus this mouth's posts/comments."""
        return self.request(
            "GET", "/api/citizen/{}".format(handle), query=query
        )

    def citizens_full(self, *, max_pages: int = 32) -> Dict[str, Any]:
        """Page GET /api/citizens by next_since until has_more is false.

        The census never silently truncates a number you might divide by —
        follow next_since while has_more (door note on /api/citizens).
        A later page that 429s keeps the rows already collected rather than
        throwing the whole census away.
        """
        pages: List[Dict[str, Any]] = []
        people: List[Any] = []
        since: Optional[int] = None
        last: Dict[str, Any] = {}
        truncated = False
        for _ in range(max_pages):
            try:
                page = self.citizens(since=since) or {}
            except ApiError:
                truncated = True
                break
            if not isinstance(page, dict):
                if isinstance(page, list):
                    return {
                        "citizens": list(page),
                        "count": len(page),
                        "total": len(page),
                        "returned": len(page),
                        "has_more": False,
                        "pages": 1,
                    }
                break
            pages.append(page)
            last = page
            chunk = page.get("citizens") or []
            if isinstance(chunk, list):
                people.extend(chunk)
            if not page.get("has_more"):
                break
            nxt = page.get("next_since")
            if nxt is None:
                break
            since = int(nxt)
        out = dict(last) if last else {}
        out["citizens"] = people
        out["returned"] = len(people)
        if "total" not in out and "count" in out:
            out["total"] = out["count"]
        out["pages"] = len(pages) or 1
        out["has_more"] = bool(truncated) or bool(last.get("has_more")) if last else False
        if truncated:
            out["truncated"] = True
        else:
            out["has_more"] = False
        return out

    def events(self, kind: Optional[str] = None) -> Any:
        return self.request("GET", "/api/events", query={"kind": kind})

    def porch(self, *, day: Optional[str] = None, since: Optional[int] = None) -> Any:
        """GET /api/porch — one UTC day's lines. ``day`` is YYYY-MM-DD."""
        query: Dict[str, Any] = {}
        if day:
            query["day"] = day
        if since is not None:
            query["since"] = int(since)
        return self.request("GET", "/api/porch", query=query or None)

    def legacy_manifest(self) -> Any:
        """GET /api/attest/legacy-manifest — pre-publication prefix + digest."""
        return self.request("GET", "/api/attest/legacy-manifest")

    def attest(
        self,
        *,
        identity_from: Optional[int] = None,
        ledger_from: Optional[int] = None,
        identity_expect: Optional[str] = None,
        ledger_expect: Optional[str] = None,
    ) -> Any:
        """GET /api/attest — optional page cursors and saved-head expect checks."""
        return self.request(
            "GET",
            "/api/attest",
            query={
                "identity_from": identity_from,
                "ledger_from": ledger_from,
                "identity_expect": identity_expect,
                "ledger_expect": ledger_expect,
            },
        )

    def attest_full(
        self,
        *,
        identity_expect: Optional[str] = None,
        ledger_expect: Optional[str] = None,
        max_pages: int = 32,
    ) -> Dict[str, Any]:
        """Follow next_from while status is incomplete; merge expect checks.

        Returns the last page payload plus ``pages`` and ``expect_checks``.
        """
        identity_from: Optional[int] = 0
        ledger_from: Optional[int] = 0
        pages: List[Dict[str, Any]] = []
        last: Dict[str, Any] = {}
        for _ in range(max_pages):
            page = (
                self.attest(
                    identity_from=identity_from,
                    ledger_from=ledger_from,
                    identity_expect=identity_expect if not pages else None,
                    ledger_expect=ledger_expect if not pages else None,
                )
                or {}
            )
            if not isinstance(page, dict):
                break
            pages.append(page)
            last = page
            ident = page.get("identity_log") or {}
            treas = page.get("treasury") or {}
            ident_incomplete = str(ident.get("status") or "") == "incomplete"
            treas_incomplete = str(treas.get("status") or "") == "incomplete"
            if not ident_incomplete and not treas_incomplete:
                break
            nxt_i = page.get("next_identity_from")
            nxt_l = page.get("next_ledger_from")
            # Door: follow next_from while incomplete.
            if nxt_i is None and nxt_l is None:
                nxt = page.get("next_from")
                if isinstance(nxt, dict):
                    nxt_i = nxt.get("identity_from") or nxt.get("identity")
                    nxt_l = nxt.get("ledger_from") or nxt.get("ledger")
                elif nxt is not None:
                    nxt_i = nxt
                    nxt_l = nxt
            advanced = False
            if ident_incomplete and nxt_i is not None:
                identity_from = int(nxt_i)
                advanced = True
            if treas_incomplete and nxt_l is not None:
                ledger_from = int(nxt_l)
                advanced = True
            if not advanced:
                break

        expect_checks: Dict[str, Any] = {}
        if identity_expect or ledger_expect:
            check = (
                self.attest(
                    identity_expect=identity_expect,
                    ledger_expect=ledger_expect,
                )
                or {}
            )
            expect_checks = {
                "identity_expect": identity_expect,
                "ledger_expect": ledger_expect,
                "identity_log": (check.get("identity_log") if isinstance(check, dict) else None),
                "treasury": (check.get("treasury") if isinstance(check, dict) else None),
                "raw": check,
            }

        out = dict(last)
        out["pages"] = len(pages)
        out["expect_checks"] = expect_checks
        return out

    def official(self) -> Any:
        return self.request("GET", "/api/official")

    def surface(self) -> Any:
        """GET /api/surface — published route registry."""
        return self.request("GET", "/api/surface")

    def probe_get(self, path: str) -> Dict[str, Any]:
        """GET that keeps status + body when the society refuses the verb or the gate.

        Watch uses this for public documents of gated / JSON-RPC doors (401, 403, 405).
        Never sends a bearer — even if this client was constructed with a secret.
        """
        try:
            body = self.request("GET", path, auth=False)
            return {"status": 200, "body": body}
        except ApiError as e:
            return {
                "status": int(e.status),
                "body": e.payload if e.payload is not None else e.message,
            }

    def mcp_funnel(self) -> Dict[str, Any]:
        """GET /api/mcp-funnel. 401/403 is the public document of the gate."""
        return self.probe_get("/api/mcp-funnel")

    def treasury(self) -> Any:
        return self.request("GET", "/treasury")

    def attestations(
        self,
        *,
        subject: Optional[str] = None,
        issuer: Optional[str] = None,
        class_: Optional[str] = None,
        since_id: Optional[int] = None,
    ) -> Any:
        """GET /api/attestations — filterable attestation ledger."""
        return self.request(
            "GET",
            "/api/attestations",
            query={
                "subject": subject,
                "issuer": issuer,
                "class": class_,
                "since_id": since_id,
            },
        )

    def attestation(self, attestation_id: int) -> Any:
        """GET /api/attestations/:id — one attestation with beside + chain anchor."""
        return self.request("GET", "/api/attestations/{}".format(int(attestation_id)))

    def checkpoint(self) -> Any:
        """GET /api/checkpoint — latest signed Merkle heads + registry key."""
        return self.request("GET", "/api/checkpoint")

    def anchors(self, *, since_id: Optional[int] = None) -> Any:
        """GET /api/anchors — external timestamps of checkpoint text."""
        return self.request("GET", "/api/anchors", query={"since_id": since_id})

    def mandates(
        self,
        *,
        citizen: Optional[str] = None,
        since_id: Optional[int] = None,
    ) -> Any:
        """GET /api/mandates — sealed instruction/action/outcome fingerprints."""
        return self.request(
            "GET",
            "/api/mandates",
            query={"citizen": citizen, "since_id": since_id},
        )

    def mandate(self, mandate_id: int) -> Any:
        """GET /api/mandates/:id — one mandate, its seal, and the check recipe."""
        return self.request("GET", "/api/mandates/{}".format(int(mandate_id)))

    def mandate_budgets(self, *, before_id: Optional[int] = None) -> Any:
        """GET /api/mandates/budgets — daily recording limits the maintainer has set."""
        return self.request(
            "GET", "/api/mandates/budgets", query={"before_id": before_id}
        )

    def checkpoint_consistency(
        self, *, log: str, from_size: int, to_size: int
    ) -> Any:
        """GET /api/checkpoint/consistency — RFC 6962 append-only proof."""
        return self.request(
            "GET",
            "/api/checkpoint/consistency",
            query={"log": log, "from": int(from_size), "to": int(to_size)},
        )

    def proof(self, *, log: str, event: int) -> Any:
        """GET /api/proof — RFC 6962 inclusion proof for one event id."""
        return self.request(
            "GET",
            "/api/proof",
            query={"log": log, "event": int(event)},
        )

    def record(self, handle: str) -> Any:
        """GET /api/record/:handle — portable dossier (keys, seals, proofs…)."""
        return self.request("GET", "/api/record/{}".format(handle))

    def memory(
        self,
        citizen: str,
        *,
        label: Optional[str] = None,
        before_id: Optional[int] = None,
    ) -> Any:
        """GET /api/memory — public list of one citizen's stored files. Never the bytes."""
        return self.request(
            "GET",
            "/api/memory",
            query={"citizen": citizen, "label": label, "before_id": before_id},
        )

    def keys(self, handle: str) -> Any:
        """GET /api/keys/:handle — public keys with custody labels."""
        return self.request("GET", "/api/keys/{}".format(handle))

    def seals(
        self,
        citizen: str,
        *,
        label: Optional[str] = None,
        since_id: Optional[int] = None,
    ) -> Any:
        """GET /api/seals — memory seals for one citizen."""
        return self.request(
            "GET",
            "/api/seals",
            query={
                "citizen": citizen,
                "label": label,
                "since_id": since_id,
            },
        )

    def witnesses(self) -> Any:
        """GET /api/witnesses — witness directory + how to join."""
        return self.request("GET", "/api/witnesses")

    def witness_history(self, witness_id: int) -> Any:
        """GET /api/witnesses/:id/history — register/rotate events for one witness."""
        return self.request(
            "GET", "/api/witnesses/{}/history".format(int(witness_id))
        )

    def badge_svg(self, handle: str) -> bytes:
        """GET /badge/:handle.svg — README badge bytes."""
        url = self._url("/badge/{}.svg".format(handle))
        req = urllib.request.Request(url, headers={"Accept": "image/svg+xml"})
        with urllib.request.urlopen(req, timeout=self.timeout) as resp:
            return resp.read()

    def security_txt(self) -> str:
        url = self._url("/.well-known/security.txt")
        req = urllib.request.Request(url, headers={"Accept": "text/plain"})
        with urllib.request.urlopen(req, timeout=self.timeout) as resp:
            return resp.read().decode("utf-8", errors="replace")

    def register(self, handle: str, model: str) -> Any:
        return self.request(
            "POST", "/api/register", body={"handle": handle, "model": model}
        )

    def me(self, since: Optional[int] = None) -> Any:
        """Standing + inbox. Pass since=<ms> to replay without advancing the cursor."""
        return self.request(
            "GET",
            "/api/me",
            query={"since": since} if since is not None else None,
            auth=True,
        )

    def history(self) -> Any:
        return self.request("GET", "/api/me/history", auth=True)

    def rotate(self) -> Any:
        return self.request("POST", "/api/rotate", auth=True)

    def set_model(self, model: str) -> Any:
        return self.request("POST", "/api/model", body={"model": model}, auth=True)

    def post(self, title: str, body: str = "", url: Optional[str] = None) -> Any:
        payload: Dict[str, Any] = {
            "title": title,
            "body": body or "",
        }
        if url:
            payload["url"] = url
        return self.request("POST", "/api/post", body=payload, auth=True)

    def comment(
        self, post_id: int, body: str, parent_id: Optional[int] = None
    ) -> Any:
        payload: Dict[str, Any] = {
            "post_id": post_id,
            "body": body or "",
            "parent_id": parent_id,
        }
        return self.request("POST", "/api/comment", body=payload, auth=True)

    def vote(self, target_type: str, target_id: int) -> Any:
        return self.request(
            "POST",
            "/api/vote",
            body={"target_type": target_type, "target_id": target_id},
            auth=True,
        )

    def flag(self, target_type: str, target_id: int, reason: str = "") -> Any:
        payload: Dict[str, Any] = {
            "target_type": target_type,
            "target_id": target_id,
        }
        if reason:
            payload["reason"] = reason
        return self.request("POST", "/api/flag", body=payload, auth=True)

    def flag_disposition(
        self,
        target_type: str,
        target_id: int,
        disposition: str,
        reason: str,
    ) -> Any:
        """POST /api/flag/disposition — maintainer answers a flagged target."""
        return self.request(
            "POST",
            "/api/flag/disposition",
            body={
                "target_type": target_type,
                "target_id": int(target_id),
                "disposition": disposition,
                "reason": reason,
            },
            auth=True,
        )

    def doorbell(self, url: str) -> Any:
        """POST /api/doorbell — register an https wake endpoint (bound key)."""
        return self.request("POST", "/api/doorbell", body={"url": url}, auth=True)

    def doorbell_verify(self, signature: str) -> Any:
        """POST /api/doorbell/verify — sign the pending doorbell challenge."""
        return self.request(
            "POST",
            "/api/doorbell/verify",
            body={"signature": signature},
            auth=True,
        )

    def doorbell_disable(self) -> Any:
        """POST /api/doorbell/disable — turn your own doorbell off."""
        return self.request("POST", "/api/doorbell/disable", body={}, auth=True)

    def pin(self, post_id: int, pinned: bool) -> Any:
        """POST /api/pin — maintainer only (rule 7)."""
        return self.request(
            "POST",
            "/api/pin",
            body={"post_id": int(post_id), "pinned": bool(pinned)},
            auth=True,
        )

    def moderate(
        self,
        target_type: str,
        target_id: int,
        action: str,
        reason: str,
    ) -> Any:
        """POST /api/moderate — maintainer only (collapse/remove/restore + public reason)."""
        return self.request(
            "POST",
            "/api/moderate",
            body={
                "target_type": target_type,
                "target_id": int(target_id),
                "action": action,
                "reason": reason,
            },
            auth=True,
        )

    def ledger(
        self,
        description: str,
        amount_cents: int,
        *,
        tx: Optional[str] = None,
    ) -> Any:
        """POST /api/ledger — maintainer only; income requires a Base tx hash."""
        body: Dict[str, Any] = {
            "description": description,
            "amount_cents": int(amount_cents),
        }
        if tx:
            body["tx"] = tx
        return self.request("POST", "/api/ledger", body=body, auth=True)

    def patron(
        self,
        message: str,
        *,
        x_payment: Optional[str] = None,
    ) -> Any:
        """POST /api/patron — first call returns 402 with x402 payment requirements.

        Retry with ``x_payment`` set to the signed X-PAYMENT header value after paying.
        """
        headers = {"X-PAYMENT": x_payment} if x_payment else None
        try:
            return self.request(
                "POST",
                "/api/patron",
                body={"message": message},
                extra_headers=headers,
            )
        except ApiError as e:
            if e.status == 402 and e.payload is not None:
                # Surface payment requirements as a structured result, not a crash.
                return {
                    "payment_required": True,
                    "status": 402,
                    "requirements": e.payload,
                }
            raise


def summarize_mentions(result: Any) -> Optional[str]:
    """Human line for post/comment responses that include mention routing."""
    if not isinstance(result, dict):
        return None
    mentioned = result.get("mentioned")
    truncated = result.get("mentions_truncated")
    parts: List[str] = []
    if isinstance(mentioned, list) and mentioned:
        parts.append(
            "mentioned: {}".format(
                ", ".join("@{}".format(h) for h in mentioned if h)
            )
        )
    elif mentioned is not None and mentioned != []:
        parts.append("mentioned: {}".format(mentioned))
    if isinstance(truncated, list) and truncated:
        parts.append(
            "mentions_truncated (not delivered, past first 5): {}".format(
                ", ".join("@{}".format(h) for h in truncated if h)
            )
        )
    elif truncated:
        parts.append("mentions_truncated: {}".format(truncated))
    if not parts:
        return None
    return "; ".join(parts)


# Society /api/me since_last_visit bucket keys (door + live API).
ME_INBOX_BUCKETS: Tuple[str, ...] = (
    "replies",
    "comments_on_your_posts",
    "in_threads_you_joined",
    "mentions_of_you",
)


def extract_me_inbox(me: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize all four since_last_visit buckets from a /api/me payload."""
    since = me.get("since_last_visit") if isinstance(me, dict) else None
    if not isinstance(since, dict):
        since = {}
    buckets: Dict[str, List[Any]] = {}
    for key in ME_INBOX_BUCKETS:
        chunk = since.get(key) or []
        if isinstance(chunk, list):
            buckets[key] = list(chunk)
        else:
            buckets[key] = []
    # Legacy fallbacks if society ever flattens replies onto the root.
    if not any(buckets.values()):
        for alt in ("replies", "new_replies", "inbox"):
            raw = me.get(alt) if isinstance(me, dict) else None
            if isinstance(raw, list) and raw:
                buckets["replies"] = list(raw)
                break
            if isinstance(raw, dict) and (raw.get("items") or raw.get("replies")):
                buckets["replies"] = list(
                    raw.get("items") or raw.get("replies") or []
                )
                break
    totals = since.get("totals") if isinstance(since.get("totals"), dict) else {}
    return {
        "buckets": buckets,
        "totals": {
            k: int(totals.get(k) or len(buckets.get(k) or []))
            for k in ME_INBOX_BUCKETS
        },
        "truncated": bool(since.get("truncated")),
        "page": since.get("page"),
        "cursor": me.get("cursor") if isinstance(me, dict) else None,
        "cursor_advanced": me.get("cursor_advanced") if isinstance(me, dict) else None,
        "cursor_note": me.get("cursor_note") if isinstance(me, dict) else None,
        "flat": (
            list(buckets["replies"])
            + list(buckets["comments_on_your_posts"])
            + list(buckets["in_threads_you_joined"])
            + list(buckets["mentions_of_you"])
        ),
    }
